In [2]:
# Importing the Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# Importing the dataset

data = pd.read_csv('grocery_store.csv', header=None)
data

         0        1        2       3
0    bread     milk  biscuit  cereal
1     milk    bread  biscuit     NaN
2    bread      tea      NaN     NaN
3      jam    bread     milk     NaN
4      tea  biscuit      NaN     NaN
5    bread      tea      NaN     NaN
6      tea   cereal      NaN     NaN
7    bread      tea  biscuit     NaN
8      jam    bread      tea     NaN
9    bread     milk      NaN     NaN
10  coffee   orange  biscuit  cereal
11  coffee   orange  biscuit  cereal
12  coffee    sugar      NaN     NaN
13   bread   coffee   orange     NaN
14   bread    sugar  biscuit     NaN
15  coffee    sugar   cereal     NaN
16   bread    sugar  biscuit     NaN
17   bread   coffee    sugar     NaN
18   bread   coffee    sugar     NaN
19     tea     milk   coffee  cereal

In [6]:
!pip install apyori

Requirement already satisfied: apyori in ./opt/anaconda3/lib/python3.7/site-packages (1.1.2)

In [14]:
transactions = []

for i in range(0,20):
    transactions.append([str(data.values[i,j]) for j in range(0,4)])

In [7]:
from apyori import apriori

In [35]:
rules = apriori(transactions, min_support=0.1, min_confidence=0.5, 
                min_lift=2, min_length=2, max_length=2 )

In [36]:
2/20

0.1

In [37]:
1/2

0.5

In [38]:
results = list(rules)

In [39]:
results

[RelationRecord(items=frozenset({'cereal', 'orange'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'orange'}), items_add=frozenset({'cereal'}), confidence=0.6666666666666667, lift=2.2222222222222228)]),
 RelationRecord(items=frozenset({'orange', 'coffee'}), support=0.15, ordered_statistics=[OrderedStatistic(items_base=frozenset({'orange'}), items_add=frozenset({'coffee'}), confidence=1.0, lift=2.5)])]

In [60]:
results[0][2][0][2]

0.6666666666666667

In [65]:
def extract(results):
    antecendents = [tuple(result[2][0][0])[0] for result in results]
    consequents =  [tuple(result[2][0][1])[0] for result in results]
    supports    =  [result[1] for result in results]
    confidences =  [result[2][0][2] for result in results]
    lifts       =  [result[2][0][3] for result in results]
    
    return list(zip(antecendents, consequents, supports, confidences, lifts))

In [62]:
list1 = [1,2]
list2 = [2,3]

list(zip(list1,list2))

[(1, 2), (2, 3)]

In [68]:
resultdf = pd.DataFrame(extract(results), 
                        columns=['antecendents', 'consequents', 'supports', 'confidences', 'lifts'])

In [70]:
resultdf.sort_values('lifts', axis=0, ascending=False)

  antecendents consequents  supports  confidences     lifts
1       orange      coffee      0.15     1.000000  2.500000
0       orange      cereal      0.10     0.666667  2.222222

In [71]:
# Importing the dataset

data = pd.read_csv('Market_Basket.csv', header=None)
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
transactions = []

for i in range(0,7501):
    transactions.append([str(data.values[i,j]) for j in range(0,20)])

In [90]:
rules = apriori(transactions, min_support=0.001, min_confidence=0.2, 
                min_lift=3, min_length=2, max_length=2 )

In [91]:
10/7501

0.0013331555792560992

In [92]:
2/10

0.2

In [93]:
results = list(rules)

In [94]:
results

[RelationRecord(items=frozenset({'barbecue sauce', 'turkey'}), support=0.0025329956005865884, ordered_statistics=[OrderedStatistic(items_base=frozenset({'barbecue sauce'}), items_add=frozenset({'turkey'}), confidence=0.2345679012345679, lift=3.751585985416831)]),
 RelationRecord(items=frozenset({'chicken', 'burger sauce'}), support=0.001599786695107319, ordered_statistics=[OrderedStatistic(items_base=frozenset({'burger sauce'}), items_add=frozenset({'chicken'}), confidence=0.2727272727272727, lift=4.546060606060606)]),
 RelationRecord(items=frozenset({'chicken', 'extra dark chocolate'}), support=0.0027996267164378083, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'chicken'}), confidence=0.23333333333333334, lift=3.8894074074074076)]),
 RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]),
 RelationRecord(items=frozenset({'chocolate bread', 'red wine'}), support=0.0010665244634048793, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate bread'}), items_add=frozenset({'red wine'}), confidence=0.25, lift=8.887440758293838)]),
 RelationRecord(items=frozenset({'cookies', 'shallot'}), support=0.001999733368884149, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shallot'}), items_add=frozenset({'cookies'}), confidence=0.25862068965517243, lift=3.2171041344999143)]),
 RelationRecord(items=frozenset({'cooking oil', 'toothpaste'}), support=0.0018664178109585388, ordered_statistics=[OrderedStatistic(items_base=frozenset({'toothpaste'}), items_add=frozenset({'cooking oil'}), confidence=0.22950819672131148, lift=4.4948850746907505)]),
 RelationRecord(items=frozenset({'corn', 'tomatoes'}), support=0.0010665244634048793, ordered_statistics=[OrderedStatistic(items_base=frozenset({'corn'}), items_add=frozenset({'tomatoes'}), confidence=0.2222222222222222, lift=3.249296079705436)]),
 RelationRecord(items=frozenset({'salmon', 'dessert wine'}), support=0.0010665244634048793, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dessert wine'}), items_add=frozenset({'salmon'}), confidence=0.2424242424242424, lift=5.700389474684145)]),
 RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'escalope', 'shallot'}), support=0.0018664178109585388, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shallot'}), items_add=frozenset({'escalope'}), confidence=0.2413793103448276, lift=3.043002028397566)]),
 RelationRecord(items=frozenset({'extra dark chocolate', 'olive oil'}), support=0.0026663111585121984, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'olive oil'}), confidence=0.22222222222222224, lift=3.3742690058479536)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.164270764485569)]),
 RelationRecord(items=frozenset({'frozen smoothie', 'sparkling water'}), support=0.0014664711371817091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'sparkling water'}), items_add=frozenset({'frozen smoothie'}), confidence=0.23404255319148937, lift=3.6959014557670775)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'tea'}), support=0.0013331555792560992, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tea'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3448275862068966, lift=3.6175548589341693)]),
 RelationRecord(items=frozenset({'pancakes', 'gluten free bar'}), support=0.0021330489268097585, ordered_statistics=[OrderedStatistic(items_base=frozenset({'gluten free bar'}), items_add=frozenset({'pancakes'}), confidence=0.3076923076923077, lift=3.2370266479663394)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'hand protein bar', 'protein bar'}), support=0.0011998400213304892, ordered_statistics=[OrderedStatistic(items_base=frozenset({'hand protein bar'}), items_add=frozenset({'protein bar'}), confidence=0.23076923076923075, lift=12.453237410071942)]),
 RelationRecord(items=frozenset({'hand protein bar', 'tomatoes'}), support=0.0011998400213304892, ordered_statistics=[OrderedStatistic(items_base=frozenset({'hand protein bar'}), items_add=frozenset({'tomatoes'}), confidence=0.23076923076923075, lift=3.3742690058479528)]),
 RelationRecord(items=frozenset({'sparkling water', 'hot dogs'}), support=0.001599786695107319, ordered_statistics=[OrderedStatistic(items_base=frozenset({'sparkling water'}), items_add=frozenset({'hot dogs'}), confidence=0.25531914893617025, lift=7.8812713422642515)]),
 RelationRecord(items=frozenset({'pancakes', 'ketchup'}), support=0.001599786695107319, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ketchup'}), items_add=frozenset({'pancakes'}), confidence=0.36363636363636365, lift=3.825576947596583)]),
 RelationRecord(items=frozenset({'ketchup', 'turkey'}), support=0.0010665244634048793, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ketchup'}), items_add=frozenset({'turkey'}), confidence=0.2424242424242424, lift=3.8772371906700265)]),
 RelationRecord(items=frozenset({'olive oil', 'light cream'}), support=0.003199573390214638, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.1147098515519573)]),
 RelationRecord(items=frozenset({'olive oil', 'whole wheat pasta'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]),
 RelationRecord(items=frozenset({'shrimp', 'pasta'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)]),
 RelationRecord(items=frozenset({'pet food', 'red wine'}), support=0.001599786695107319, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pet food'}), items_add=frozenset({'red wine'}), confidence=0.2448979591836735, lift=8.706064416287843)]),
 RelationRecord(items=frozenset({'pet food', 'turkey'}), support=0.0013331555792560992, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pet food'}), items_add=frozenset({'turkey'}), confidence=0.20408163265306123, lift=3.2640006962273187)])]

In [95]:
resultdf = pd.DataFrame(extract(results), 
                        columns=['antecendents', 'consequents', 'supports', 'confidences', 'lifts'])

In [97]:
resultdf.sort_values('lifts', axis=0, ascending=False)

            antecendents        consequents  supports  confidences      lifts
19      hand protein bar        protein bar  0.001200     0.230769  12.453237
4        chocolate bread           red wine  0.001067     0.250000   8.887441
27              pet food           red wine  0.001600     0.244898   8.706064
21       sparkling water           hot dogs  0.001600     0.255319   7.881271
8           dessert wine             salmon  0.001067     0.242424   5.700389
13         fromage blanc              honey  0.003333     0.245098   5.164271
3            light cream            chicken  0.004533     0.290598   4.843951
10                 pasta           escalope  0.005866     0.372881   4.700812
1           burger sauce            chicken  0.001600     0.272727   4.546061
26                 pasta             shrimp  0.005066     0.322034   4.506672
6             toothpaste        cooking oil  0.001866     0.229508   4.494885
25     whole wheat pasta          olive oil  0.007999     0.271493   4.122410
2   extra dark chocolate            chicken  0.002800     0.233333   3.889407
23               ketchup             turkey  0.001067     0.242424   3.877237
18          tomato sauce        ground beef  0.005333     0.377358   3.840659
22               ketchup           pancakes  0.001600     0.363636   3.825577
9   mushroom cream sauce           escalope  0.005733     0.300699   3.790833
0         barbecue sauce             turkey  0.002533     0.234568   3.751586
14       sparkling water    frozen smoothie  0.001466     0.234043   3.695901
15                   tea  frozen vegetables  0.001333     0.344828   3.617555
12  extra dark chocolate          olive oil  0.002666     0.222222   3.374269
20      hand protein bar           tomatoes  0.001200     0.230769   3.374269
17         herb & pepper        ground beef  0.015998     0.323450   3.291994
28              pet food             turkey  0.001333     0.204082   3.264001
7                   corn           tomatoes  0.001067     0.222222   3.249296
16       gluten free bar           pancakes  0.002133     0.307692   3.237027
5                shallot            cookies  0.002000     0.258621   3.217104
24           light cream          olive oil  0.003200     0.205128   3.114710
11               shallot           escalope  0.001866     0.241379   3.043002

In [ ]:
# Machine Learning - Supervised Learning
# 1.Regression - Linear, Polynomial, Support Vector regression(task)
# 2.Classification - Logistic, Decision Trees(both) , Random Forests(both), Support Vector Machines(class), 
    #Naive Bayes 
# 3. Neural Networks (Deep Learning) 
    
    
# Unsupervised
# 1. Clustering
# 2. Dimensionality reduction